# Generated by Django 6.0.7 on 2026-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
