# Generated by Django 6.0.7 on 2026-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_section_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
