# Generated by Django 6.0.7 on 2026-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_sectionitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
