# Generated by Django 6.0.7 on 2026-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_sectionitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='is_present',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='organization',
            field=models.CharField(blank=True, null=True),
        ),
    ]
