# Generated by Django 6.0.7 on 2026-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_sectionitem_is_present_sectionitem_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
